# Generated by Django 6.0.6 on 2026-06-16 05:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('job_type', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('minimum_salary', models.PositiveBigIntegerField()),
                ('maximum_salary', models.PositiveBigIntegerField()),
                ('job_description', models.TextField()),
                ('application_email', models.EmailField(max_length=254)),
                ('attended_to', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
