# Generated by Django 6.0.6 on 2026-06-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postjob', '0002_applyjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
