# Generated by Django 6.0.6 on 2026-06-15 10:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('job_type', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('minimum_salary', models.PositiveBigIntegerField()),
                ('maximum_salary', models.PositiveBigIntegerField()),
                ('job_description', models.TextField()),
                ('application_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
