# Generated by Django 6.0.6 on 2026-06-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0002_joblist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobList',
        ),
    ]
